version: "3.9"
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clon-trello
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
